C_OBJS=sqlite3.o sqlite_test.o
ASM_OBJS=
COMPONENT=sqlite_torrent_test1.o
INTERFACES=
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt mem_mgr_large valloc lock
IF_LIB=

include ../../Makefile.subsubdir


